// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjwCo1HPQMaaUbxDvqej6nvhjH_irNG7U',
    appId: '1:363180835744:web:215ff70e0878ca25e65ac5',
    messagingSenderId: '363180835744',
    projectId: 'woila-chicken',
    authDomain: 'woila-chicken.firebaseapp.com',
    storageBucket: 'woila-chicken.firebasestorage.app',
    measurementId: 'G-TXC5ET2ZVX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcPAyS4i3p6nhpIKtpGO3w3R4ma1L29VU',
    appId: '1:363180835744:android:7bd042ea0f7332b3e65ac5',
    messagingSenderId: '363180835744',
    projectId: 'woila-chicken',
    storageBucket: 'woila-chicken.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhOZmk96LUILHyZer0Ke6471_n-l-uM2E',
    appId: '1:363180835744:ios:47eac523cf3213a4e65ac5',
    messagingSenderId: '363180835744',
    projectId: 'woila-chicken',
    storageBucket: 'woila-chicken.firebasestorage.app',
    iosBundleId: 'com.woilachicken.woilaChicken',
  );
}
